# -*- coding: utf-8 -*-
"""JsonToCsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYYmFp8qbTMi-T9NpWtcU-S6zfbKy4aS
"""

!pip install pandas

import pandas as pd
import json

# Replace with your actual file name
file_name = "/daikibo-telemetry-data.json"

# Load JSON data
with open(file_name) as f:
    data = json.load(f)

# Flatten the JSON using json_normalize
from pandas import json_normalize

df = json_normalize(
    data,
    sep='_'
)

# Display the first few rows to check
df.head()

# Save as CSV
df.to_csv("flattened_daikibo.csv", index=False)

import os
os.listdir()